#!/usr/bin/bash

if [ "$1" = "-c" -a "$2" = "ECC" ];then #attention à l 'espace
  openssl ecparam -out ecc.ca.key.pem -name prime256v1 -genkey
  openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:TRUE") -new -nodes -subj "/C=FR/L=Limoges/O=CertifPlus/OU=SecuTic/CN=web_service" -x509 -extensions ext -sha256 -key ecc.ca.key.pem -text -out ecc.ca.cert.pem
  openssl ecparam -out ecc.key.pem -name prime256v1 -genkey
  openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:FALSE") -new -subj "/C=FR/L=Limoges/O=CertifPlus/OU=SecuTic/CN=Student" -reqexts ext -sha256 -key ecc.key.pem -text -out ecc.csr.pem
  openssl x509 -req -days 3650 -CA ecc.ca.cert.pem -CAkey ecc.ca.key.pem -CAcreateserial -extfile <(printf "basicConstraints=critical,CA:FALSE") -in ecc.csr.pem -text  -out ecc.serveur.pem
  rm ecc.ca.cert.srl ecc.ca.key.pem ecc.csr.pem 
fi

if [ "$1" = "-r" -a "$3" = "-r" ]; then
  if [ "$2" = "identite" -a "$4" = "intitule_certif" ]; then
    curl -X POST -d 'identite=Akkouche Adam' -d 'intitule_certif=SecuTIC' \
    http://localhost:8080/creation
  fi
fi

if [ "$1" = "-h" -a "$2" = "y" ]; then
  openssl ts -query -data time_stamp -no_nonce -sha512 -cert -out query.tsq
  curl -H 'Content-Type: application/timestamp-query' --data-binary '@query.tsq' https://freetsa.org/tsr > response.tsr
  rm query.tsq
fi

if [ "$1" = "-s" -a "$2" = "RSA" ]; then
  openssl genrsa -out cle_privee.pem 2048 #génère une cle privée
  openssl rsa -in cle_privee.pem -pubout -out rsaclefpublique.pem #génère une clef publique dérivée
  openssl rsautl -sign -inkey cle_privee.pem -in post_txt -out signature.sig #génère une signature du fichier contenant le poster de l'user
  openssl base64 -in signature.sig -out sign
fi
